# Ministério das Mulheres - MMulheres {.unnumbered}

O **Ministério das Mulheres** é responsável pela formulação, coordenação e execução de políticas e diretrizes de garantia dos direitos das mulheres. Cabe ao Ministério das Mulheres também a articulação intersetorial e transversal junto aos órgãos públicos nos três níveis de gestão (União, estados e municípios), entidades públicas e privadas e organizações da sociedade civil.

Também é papel do Ministério das Mulheres a elaboração e implementação de campanhas educativas e antidiscriminatórias de abrangência nacional. Cabe ainda ao MMulheres a promoção e execução de programas de cooperação com organismos nacionais e internacionais, públicos ou privados, para a implementação de políticas para mulheres, e o acompanhamento do cumprimento de legislação sobre ações afirmativas, bem como a definição de ações para o cumprimento de acordos, convenções e planos de ação a respeito da garantia da igualdade de gênero e do combate à discriminação.

Além do gabinete e assessoria direta à ministra, o Ministério das Mulheres é composto por uma secretaria executiva e três secretarias nacionais: de Articulação Institucional, Ações Temáticas e Participação Política (SENATP); de Autonomia Econômica e Política de Cuidados (SENAEC); e de Enfrentamento à Violência contra Mulheres (SENEV).

# Secretaria Executiva - SE {.unnumbered}

Cabe à Secretaria Executiva (SE) assistir a ministra de Estado na definição de diretrizes, no planejamento estratégico e na coordenação e supervisão das atividades do Ministério das Mulheres. Além de ser responsável por apoiar e elaborar a formulação, a articulação e a implementação, no âmbito do Poder Executivo federal, do Plano Nacional de Políticas para as Mulheres, e de outras ações e programas referentes às políticas para as mulheres. Além disso, SE desenvolve atividades relacionadas aos sistemas de informação e gestão do governo federal, tais como os Sistemas de Planejamento e de Orçamento Federal, de Administração Financeira Federal (Siafi), de Gestão de documentos e Arquivos (Siga) e de Pessoal Civil da Administração Federal (Sipec), entre outros.

A Secretaria Executiva é responsável ainda pela organização e manutenção do acervo bibliográfico sobre políticas para mulheres e igualdade de gênero do Ministério das Mulheres e coordena as atividades relacionadas ao Observatório Brasil da Igualdade de Gênero.

# Secretaria Nacional de Enfrentamento à Violência contra Mulheres - Senev {.unnumbered}

A Secretaria Nacional de Enfrentamento à Violência contra Mulheres (SENEV) coordena, pelo Ministério das Mulheres, a formulação de políticas de enfrentamento à violência contra mulheres em diversos aspectos, que vão da prevenção até à assistência às mulheres em situação de violência.

A SENEV é responsável pela gestão da Central de Atendimento à Mulher, o [**Ligue 180**](https://www.gov.br/mulheres/pt-br/ligue-180), destinado a receber denúncias e reclamações e prestar informações sobre o tema, e pela implantação de [**Casas da Mulher da Brasileira**](https://www.gov.br/mulheres/pt-br/acesso-a-informacao/acoes-e-programas-1/casa-da-mulher-brasileira), em parceria com estados e municípios.

Realiza ainda estudos e pesquisas com vistas à redução do feminicídio ou assassinatos de meninas e mulheres por arma de fogo.

# Secretaria Nacional de Articulação Institucional, Ações Temáticas e Participação Política - Senatp {.unnumbered}

A Secretaria Nacional de Articulação Institucional, Ações Temáticas e Participação Política (SENATP) coordena a formulação e execução de políticas para mulheres nas áreas de educação, cultura, saúde e participação política, que considerem sua diversidade racial, étnica, dos povos originários e tradicionais, de orientação sexual, de identidade de gênero, geracional, territorial e das mulheres com deficiências, entre outras.

Atua ainda na formação de agentes públicos e articula, com outros órgãos da administração pública – da União, dos estados e dos municípios, a incorporação da perspectiva de gênero na elaboração e implementação das políticas públicas.

Busca o fortalecimento de políticas para mulheres nos estados e municípios e também fomenta a participação política das mulheres.

# Secretaria Nacional de Autonomia Econômica e Politica de Cuidados - Senaec {.unnumbered}

As questões de gênero relacionadas ao mundo do trabalho, à autonomia econômica das mulheres e às políticas de cuidados são o principal foco da Secretaria Nacional de Autonomia Econômica (SENAEC). Cabe a esta Secretaria desenvolver e divulgar estudos, projetos e pesquisas transversais sobre estas temáticas, bem como elaborar a política nacional de cuidados, como forma de reduzir a sobrecarga de trabalho das mulheres, que quase sempre dividem a vida profissional com atividades de assistência a suas famílias.\
\
A SENAEC também trabalha na articulação e acompanhamento dos diferentes mecanismos de combate à pobreza, à fome e ao desemprego de mulheres e também formula e monitora programas e projetos para as mulheres nas áreas de trabalho, autonomia econômica e política de cuidados.
